VERSION = '0.0.11.dev1'

DEFAULT_QUEUE = 'spinach'
DEFAULT_NAMESPACE = 'spinach'
DEFAULT_MAX_RETRIES = 0
DEFAULT_ENQUEUE_JOB_RETRIES = 4
DEFAULT_WORKER_NUMBER = 5

FUTURE_JOBS_KEY = '_future-jobs'
RUNNING_JOBS_KEY = '_running-jobs-on-broker-{}'
NOTIFICATIONS_KEY = '_notifications'
PERIODIC_TASKS_HASH_KEY = '_periodic_tasks_hash'
PERIODIC_TASKS_QUEUE_KEY = '_periodic_tasks_queue'

WAIT_FOR_EVENT_MAX_SECONDS = 60
