[tox]
envlist = py3, pep8

[testenv]
basepython = python3
envdir =
    py3: {toxworkdir}/py3
    pep8: {toxworkdir}/py3
usedevelop = True
allowlist_externals =
    docker
deps =
    aiosql
    pytest
    pytest-cov
    pytest-threadleak
    pycodestyle
    flake8
    flask
    django
    psycopg[binary]>=3.1
    psycopg_pool>=3.1
setenv =
    SPINACH_TEST_POSTGRES_DSN = postgresql://postgres@127.0.0.1:5432/spinach

[testenv:pep8]
commands =
    pycodestyle --ignore=E252,W503,W504 spinach tests

[testenv:py3]
commands_pre = docker compose -f {toxinidir}/tests/docker-compose.yml up -d --wait
commands = pytest tests {posargs}
commands_post = docker compose -f {toxinidir}/tests/docker-compose.yml down
